# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QtWidgetsApplication1
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"../opencv" \
    -L"../openzen" \
    -L"../kinect" \
    -lOpenZen \
    -lk4a \
    -lk4arecord \
    -lopencv_world3414 \
    -lopencv_world3414d
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
